mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.rainbow.blog.mapper: debug

logging:
  level:
    root: info


server:
  port: 10000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:jdbc: mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
